# Generated by Django 4.0.5 on 2022-06-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_about', models.CharField(max_length=40)),
                ('details_about', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AddGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('photo_game', models.ImageField(blank=True, null=True, upload_to='')),
                ('logo_game', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name_plural': 'sign in',
                'db_table': 'app_sign in',
            },
        ),
    ]
