# Generated by Django 4.2.11 on 2024-05-24 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_about', models.CharField(max_length=40)),
                ('details_about', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AddGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('photo_game', models.ImageField(blank=True, default='https://placehold.co/600x400', null=True, upload_to='challenge')),
                ('logo_game', models.ImageField(blank=True, default='https://placehold.co/600x400', null=True, upload_to='challenge')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('photo_game', models.ImageField(blank=True, default='https://placehold.co/600x400', null=True, upload_to='challenge')),
                ('games', models.CharField(choices=[('hh', 'hh')], null=True)),
                ('description', models.TextField(null=1)),
                ('prizes', models.TextField(null=1)),
                ('notes', models.TextField(null=1)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenge_me.addgame', to_field='name')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tournament', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tournament', to='challenge_me.tournament')),
            ],
        ),
    ]
