# Generated by Django 4.2.11 on 2025-05-03 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge_me', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='slug',
        ),
    ]
