# Generated by Django 4.0.5 on 2023-10-02 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenge_me', '0002_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='addgame',
            name='tournaments',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='challenge_me.tournament'),
            preserve_default=False,
        ),
    ]
