# Generated by Django 4.0.5 on 2023-10-02 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenge_me', '0003_addgame_tournaments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addgame',
            name='tournaments',
        ),
        migrations.AddField(
            model_name='tournament',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='challenge_me.addgame'),
        ),
    ]
