# Generated by Django 4.2.11 on 2025-05-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge_me', '0004_remove_game_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='is_active',
            field=models.BooleanField(default=True, null=1),
        ),
    ]
