# Generated by Django 4.0.5 on 2023-10-02 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge_me', '0004_remove_addgame_tournaments_tournament_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addgame',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
