# Generated by Django 4.0.5 on 2023-10-02 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenge_me', '0006_alter_tournament_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=100)),
                ('tournament', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='challenge_me.tournament')),
            ],
        ),
    ]
