# Generated by Django 4.2.11 on 2025-06-08 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenge_me', '0006_tournamentregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='photo_game_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='tournamentregistration',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player', to=settings.AUTH_USER_MODEL, verbose_name='player'),
        ),
    ]
