# Generated by Django 4.0.5 on 2023-10-02 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge_me', '0007_players'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Players',
            new_name='Player',
        ),
    ]
