# Generated by Django 4.2.11 on 2025-06-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge_me', '0007_game_photo_game_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='logo_game',
            field=models.ImageField(blank=True, null=True, upload_to='challenge'),
        ),
        migrations.AlterField(
            model_name='game',
            name='photo_game',
            field=models.ImageField(blank=True, null=True, upload_to='challenge'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='photo_game',
            field=models.ImageField(blank=True, null=True, upload_to='challenge'),
        ),
    ]
