# Generated by Django 4.2.11 on 2025-06-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge_me', '0008_alter_game_logo_game_alter_game_photo_game_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='logo_game_url',
            field=models.URLField(null=True),
        ),
    ]
