# Generated by Django 4.2.11 on 2025-06-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge_me', '0009_game_logo_game_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='logo_game_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='photo_game_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
