# Generated by Django 3.2 on 2023-10-17 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge_me', '0010_alter_player_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='description',
            field=models.TextField(null=1),
            preserve_default=1,
        ),
        migrations.AddField(
            model_name='tournament',
            name='notes',
            field=models.TextField(null=1),
            preserve_default=1,
        ),
        migrations.AddField(
            model_name='tournament',
            name='prizes',
            field=models.TextField(null=1),
            preserve_default=1,
        ),
    ]
