# Generated by Django 4.2.11 on 2025-06-09 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge_me', '0010_alter_game_logo_game_url_alter_game_photo_game_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='logo_game',
            field=models.ImageField(blank=True, default='https://placehold.co/600x400', null=True, upload_to='challenge'),
        ),
        migrations.AlterField(
            model_name='game',
            name='logo_game_url',
            field=models.URLField(blank=True, default='https://placehold.co/600x400', null=True),
        ),
    ]
