# Generated by Django 3.2 on 2023-10-28 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge_me', '0011_auto_20231017_2049'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Form',
        ),
        migrations.AlterField(
            model_name='addgame',
            name='logo_game',
            field=models.ImageField(blank=True, null=True, upload_to='challenge'),
        ),
        migrations.AlterField(
            model_name='addgame',
            name='photo_game',
            field=models.ImageField(blank=True, null=True, upload_to='challenge'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='photo_game',
            field=models.ImageField(blank=True, null=True, upload_to='challenge'),
        ),
    ]
