# Generated by Django 3.2 on 2023-10-29 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenge_me', '0012_auto_20231029_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='game',
            field=models.ForeignKey(db_column='game', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='challenge_me.addgame'),
        ),
    ]
