# Generated by Django 4.2.11 on 2025-06-09 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge_me', '0012_alter_game_logo_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='logo_game',
            field=models.ImageField(blank=True, default='media/image2.jpg', null=True, upload_to='challenge'),
        ),
    ]
