# Generated by Django 4.2.11 on 2024-05-24 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge_me', '0014_alter_tournament_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='games',
            field=models.CharField(choices=[('valorant', 'valorant')], null=1),
            preserve_default=1,
        ),
    ]
