# Generated by Django 4.2.11 on 2024-05-24 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge_me', '0015_tournament_games'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='games',
            field=models.CharField(choices=[('clash royal', 'clash royal'), ('valorant', 'valorant')], null=1),
        ),
    ]
