# Generated by Django 4.2.11 on 2025-06-09 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge_me', '0015_alter_game_logo_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='logo_game',
            field=models.ImageField(blank=True, default='challenge/challenge.png', null=True, upload_to='challenge'),
        ),
        migrations.AlterField(
            model_name='game',
            name='logo_game_url',
            field=models.URLField(blank=True, default='https://res.cloudinary.com/dnru0whph/image/upload/v1749457758/media/challenge/challenge_me.png', null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='photo_game',
            field=models.ImageField(blank=True, default='challenge/challenge.png', null=True, upload_to='challenge'),
        ),
        migrations.AlterField(
            model_name='game',
            name='photo_game_url',
            field=models.URLField(blank=True, default='https://res.cloudinary.com/dnru0whph/image/upload/v1749457758/media/challenge/challenge_me.png', null=True),
        ),
    ]
