# Generated by Django 4.2.11 on 2025-06-09 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge_me', '0016_alter_game_logo_game_alter_game_logo_game_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='logo_game',
            field=models.ImageField(blank=True, default='challenge/challenge_me.png', null=True, upload_to='challenge'),
        ),
        migrations.AlterField(
            model_name='game',
            name='photo_game',
            field=models.ImageField(blank=True, default='challenge/challenge_me.png', null=True, upload_to='challenge'),
        ),
    ]
