# Generated by Django 4.2.11 on 2024-05-24 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge_me', '0017_alter_tournament_games'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='games',
        ),
    ]
