# Generated by Django 4.2.11 on 2024-05-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge_me', '0018_remove_tournament_games'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addgame',
            name='logo_game',
            field=models.ImageField(blank=True, default='https://placehold.co/600x400', null=True, upload_to='challenge'),
        ),
        migrations.AlterField(
            model_name='addgame',
            name='photo_game',
            field=models.ImageField(blank=True, default='https://placehold.co/600x400', null=True, upload_to='challenge'),
        ),
    ]
