# Generated by Django 4.2.11 on 2025-06-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge_me', '0018_alter_game_logo_game_url_alter_game_photo_game_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='logo_game_url',
            field=models.URLField(blank=True, default='https://res.cloudinary.com/dnru0whph/image/upload/v1749458914/media/challenge/challenge_me.png', null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='photo_game_url',
            field=models.URLField(blank=True, default='https://res.cloudinary.com/dnru0whph/image/upload/v1749458914/media/challenge/challenge_me.png', null=True),
        ),
    ]
