# Generated by Django 4.2.11 on 2025-06-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge_me', '0019_alter_game_logo_game_url_alter_game_photo_game_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='max_participants',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
