# Generated by Django 4.2.11 on 2024-05-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge_me', '0019_alter_addgame_logo_game_alter_addgame_photo_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='games',
            field=models.CharField(choices=[('clash royal', 'clash royal'), ('valorant', 'valorant')], null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='photo_game',
            field=models.ImageField(blank=True, default='https://placehold.co/600x400', null=True, upload_to='challenge'),
        ),
    ]
