# Generated by Django 4.2.11 on 2025-08-08 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge_me', '0020_tournament_max_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='logo_game',
            field=models.ImageField(blank=True, null=True, upload_to='challenge'),
        ),
        migrations.AlterField(
            model_name='game',
            name='logo_game_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='photo_game',
            field=models.ImageField(blank=True, null=True, upload_to='challenge'),
        ),
        migrations.AlterField(
            model_name='game',
            name='photo_game_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
